// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.7.0_magicast@0.3.5_rollup@4.24.4_typescript@5.7.2_vue@3.5.13_typescript@5.7.2_/node_modules/@pinia/nuxt/dist/runtime/payload-plugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@20.11.17_ioredis@5.4.1_magicast@0.3.5_rollup@_oqxwsftkumkwsu7qz2upnbtjg4/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@20.11.17_ioredis@5.4.1_magicast@0.3.5_rollup@_oqxwsftkumkwsu7qz2upnbtjg4/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@20.11.17_ioredis@5.4.1_magicast@0.3.5_rollup@_oqxwsftkumkwsu7qz2upnbtjg4/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@20.11.17_ioredis@5.4.1_magicast@0.3.5_rollup@_oqxwsftkumkwsu7qz2upnbtjg4/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@20.11.17_ioredis@5.4.1_magicast@0.3.5_rollup@_oqxwsftkumkwsu7qz2upnbtjg4/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@20.11.17_ioredis@5.4.1_magicast@0.3.5_rollup@_oqxwsftkumkwsu7qz2upnbtjg4/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@20.11.17_ioredis@5.4.1_magicast@0.3.5_rollup@_oqxwsftkumkwsu7qz2upnbtjg4/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.7.0_magicast@0.3.5_rollup@4.24.4_typescript@5.7.2_vue@3.5.13_typescript@5.7.2_/node_modules/@pinia/nuxt/dist/runtime/plugin.vue3.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@20.11.17_ioredis@5.4.1_magicast@0.3.5_rollup@_oqxwsftkumkwsu7qz2upnbtjg4/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@20.11.17_ioredis@5.4.1_magicast@0.3.5_rollup@_oqxwsftkumkwsu7qz2upnbtjg4/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@1.6.0_rollup@4.24.4_vite@5.4.10_@types+node@20.11.17_terser@5.36.0__vue@3.5.13_typescript@5.7.2_/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@1.6.0_rollup@4.24.4_vite@5.4.10_@types+node@20.11.17_terser@5.36.0__vue@3.5.13_typescript@5.7.2_/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+content@2.13.4_ioredis@5.4.1_magicast@0.3.5_nuxt@3.14.159_@parcel+watcher@2.5.0_@types+_fh3hmswv65fje6ad4im3qt7fva/node_modules/@nuxt/content/dist/runtime/plugins/ws.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+content@2.13.4_ioredis@5.4.1_magicast@0.3.5_nuxt@3.14.159_@parcel+watcher@2.5.0_@types+_fh3hmswv65fje6ad4im3qt7fva/node_modules/@nuxt/content/dist/runtime/legacy/plugins/documentDriven.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@2.19.2_axios@1.7.7_change-case@5.4.4_jwt-decode@3.1.2_magicast@0.3.5_rollup@4.24.4_s_cla7d6oojom2r2eja4c22p4gii/node_modules/@nuxt/ui/dist/runtime/plugins/slideovers.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@2.19.2_axios@1.7.7_change-case@5.4.4_jwt-decode@3.1.2_magicast@0.3.5_rollup@4.24.4_s_cla7d6oojom2r2eja4c22p4gii/node_modules/@nuxt/ui/dist/runtime/plugins/modals.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@2.19.2_axios@1.7.7_change-case@5.4.4_jwt-decode@3.1.2_magicast@0.3.5_rollup@4.24.4_s_cla7d6oojom2r2eja4c22p4gii/node_modules/@nuxt/ui/dist/runtime/plugins/colors.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.3.5_rollup@4.24.4/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.3.5_rollup@4.24.4/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+icon@1.10.2_magicast@0.3.5_rollup@4.24.4_vite@5.4.10_@types+node@20.11.17_terser@5.36.0_kh4xy3n7sipchigspzmyraeipi/node_modules/@nuxt/icon/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-icon@1.0.0-beta.7_magicast@0.3.5_rollup@4.24.4_vite@5.4.10_@types+node@20.11.17_terser@5_j5uxw34cd6kkam5baou3ttpyli/node_modules/nuxt-icon/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@20.11.17_ioredis@5.4.1_magicast@0.3.5_rollup@_oqxwsftkumkwsu7qz2upnbtjg4/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@20.11.17_ioredis@5.4.1_magicast@0.3.5_rollup@_oqxwsftkumkwsu7qz2upnbtjg4/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")> &
  InjectionType<typeof import("../../src/plugins/vue-the-mask.client.js")> &
  InjectionType<typeof import("../../src/plugins/api")> &
  InjectionType<typeof import("../../src/plugins/serviceWorker.js")> &
  InjectionType<typeof import("../../src/plugins/vue3-toastify")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'pinia' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | '@nuxt/icon' | 'nuxt-icon' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
